# Generated by Django 4.2.1 on 2023-05-28 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norosite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image_address',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
