# Generated by Django 4.2.1 on 2023-05-28 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norosite', '0002_remove_customer_image_address_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='norosite\\static\\images')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='image_address',
            field=models.ManyToManyField(blank=True, related_name='image_field', to='norosite.image'),
        ),
    ]
